mixed-port: 7890
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
ipv6: false
dns:
  enabled: true
  ipv6: false
  nameserver: # 8848
    - 1.2.4.8 # 1.2.4.8
    - 223.5.5.5 # 阿里云 DNS （偏爱）
    - 223.6.6.6 # 阿里云 DNS （偏爱）
    - 119.29.29.29 # DNSPod DNS （偏爱）
    - 180.76.76.76 # 百度云 DNS
    - 183.60.83.19 # 腾讯云 DNS
    - 183.60.82.98 # 腾讯云 DNS
    - 114.114.114.114 # 114 DNS
    - tls://13800000000.rubyfish.cn:853
    - https://13800000000.rubyfish.cn/
  fallback:
    - 8.8.8.8 # Google DNS （偏爱）
    - 8.8.4.4 # Google DNS （偏爱）
    - tls://1.0.0.1:853 # （偏爱）
    - tls://dns.google:853 # （偏爱）
    - tls://13800000000.rubyfish.cn:853
  fallback-filter:
    geoip: true # 默认
    ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
      - 240.0.0.0/4