
config status 'status'

config config 'config'
	option enabled '1'
	option profile 'file:nikki.yaml'
	option start_delay '5'
	option scheduled_restart '0'
	option test_profile '0'
	option fast_reload '1'
	option cron_expression '0 3 * * *'

config proxy 'proxy'
	option enabled '1'
	option tcp_mode 'redirect'
	option udp_mode 'tun'
	option ipv4_dns_hijack '1'
	option ipv6_dns_hijack '1'
	option ipv4_proxy '1'
	option ipv6_proxy '0'
	option fake_ip_ping_hijack '1'
	option router_proxy '1'
	option lan_proxy '1'
	list lan_inbound_interface 'lan'
	list lan_inbound_interface 'wgvpn'
	option bypass_china_mainland_ip '0'
	option proxy_tcp_dport '0-65535'
	option proxy_udp_dport '0-65535'
	list bypass_dscp '4'

config subscription 'subscription'
	option name 'nikki'
	option url 'https://gh-proxy.com/https://raw.githubusercontent.com/Heart-Stealer/myclash/main/nikkitest.yaml'
	option user_agent 'clash'
	option prefer 'local'

config mixin 'mixin'
	option log_level 'warning'
	option mode 'rule'
	option match_process 'off'
	# option outbound_interface 'usb'
	option ipv6 '1'
	option unify_delay '1'
	option tcp_concurrent '1'
	option disable_tcp_keep_alive '0'
	option tcp_keep_alive_idle '600'
	option tcp_keep_alive_interval '30'
	option global_client_fingerprint 'chrome'
	option ui_path 'ui'
	option ui_name 'zashboard'
	option ui_url 'https://gh-proxy.com/https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip'
	option api_listen '[::]:9090'
	option api_secret '963.'
	option selection_cache '1'
	option allow_lan '1'
	option http_port '7891'
	option socks_port '7892'
	option mixed_port '7890'
	option redir_port '7893'
	option tproxy_port '7894'
	option authentication '0'
	option tun_device 'nikki'
	option tun_stack 'mixed'
	option tun_mtu '9000'
	option tun_gso '1'
	option tun_gso_max_size '65536'
	option tun_endpoint_independent_nat '0'
	option tun_dns_hijack '1'
	option dns_listen '[::]:1053'
	option dns_ipv6 '1'
	option dns_mode 'fake-ip'
	option fake_ip_range '28.0.0.1/8'
	option fake_ip_filter '0'
	option fake_ip_filter_mode 'blacklist'
	option fake_ip_cache '1'
	option dns_respect_rules '1'
	option dns_doh_prefer_http3 '0'
	option dns_system_hosts '0'
	option dns_hosts '1'
	option hosts '1'
	option dns_nameserver '1'
	option dns_nameserver_policy '0'

	option sniffer '1'
	option sniffer_sniff_dns_mapping '1'
	option sniffer_sniff_pure_ip '1'
	option sniffer_force_domain_name '0'
	option sniffer_ignore_domain_name '0'
	option sniffer_sniff '0'

	option rule_provider '0'
	option rule '0'
	option mixin_file_content '0'

	option geoip_format 'dat'
	option geodata_loader 'memconservative'
	option geosite_url 'https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat'
	option geoip_mmdb_url 'https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb'
	option geoip_dat_url 'https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat'
	# option geoip_asn_url 'https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb'
	option geox_auto_update '1'
	option geox_update_interval '48'

	list fake_ip_filters 'geosite:cn'
	list fake_ip_filters 'geosite:category-games'
	list fake_ip_filters 'RULE-SET:aa-fakeip'
	# list fake_ip_filters '+.localdomain'
	# list fake_ip_filters '+.vivo.com.cn'
	# list fake_ip_filters 'Mijia Cloud'
	# list fake_ip_filters '+.market.xiaomi.com'
	# list fake_ip_filters '+.msftconnecttest.com'
	# list fake_ip_filters '+.msftncsi.com'
	# list fake_ip_filters '+.qq.com'
	# list fake_ip_filters '+.tencent.com'
	# list fake_ip_filters '+.steamcontent.com'
	# list fake_ip_filters 'xbox.*.*.microsoft.com'
	# list fake_ip_filters '*.*.xboxlive.com'
	# list fake_ip_filters 'xbox.*.microsoft.com'
	# list fake_ip_filters 'xnotify.xboxlive.com'
	# list fake_ip_filters 'stun.*.*'
	# list fake_ip_filters '+.stun.*.*'
	# list fake_ip_filters '+.nflxvideo.net'
	# list fake_ip_filters 'time.*.com'
	# list fake_ip_filters 'time.*.gov'
	# list fake_ip_filters 'time.*.edu.cn'
	# list fake_ip_filters 'time.*.apple.com'
	# list fake_ip_filters 'ntp.*.com'
	# list fake_ip_filters 'WORKGROUP'
	# list fake_ip_filters '+.kyarucloud.moe'
	# list fake_ip_filters '+.dynv6.com'
	list sniffer_force_domain_names '+.v2ex.com'
	list sniffer_force_domain_names '+.google.com'
	list sniffer_force_domain_names '+.netflix.com'
	list sniffer_force_domain_names '+.nflxvideo.net'
	list sniffer_ignore_domain_names 'Mijia Cloud'
	list sniffer_ignore_domain_names 'dlg.io.mi.com'
	list sniffer_ignore_domain_names '*.push.apple.com'
	list sniffer_ignore_domain_names '+.apple.com'
	list sniffer_ignore_domain_names '+.oray.com'
	list sniffer_ignore_domain_names '+.sunlogin.net'
	list tun_dns_hijacks 'any:53'
	list tun_dns_hijacks 'tcp://any:53'
	list tun_dns_hijacks 'udp://any:53'

config env 'env'
	option disable_safe_path_check '0'
	option disable_loopback_detector '0'
	option disable_quic_go_gso '0'
	option disable_quic_go_ecn '0'

config authentication
	option enabled '0'
	option username 'nikki'
	option password '963.'

config nameserver
	option enabled '1'
	option type 'default-nameserver'
	list nameserver '223.5.5.5'
	list nameserver '119.29.29.29'
	# list nameserver '222.222.222.222'

config nameserver
	option enabled '1'
	option type 'proxy-server-nameserver'
	list nameserver 'https://dns.alidns.com/dns-query'
	list nameserver 'https://doh.pub/dns-query'
	list nameserver 'https://dns.google/dns-query'

config nameserver
	option enabled '0'
	option type 'direct-nameserver'

config nameserver
	option enabled '1'
	option type 'nameserver'
	list nameserver '223.5.5.5'
	list nameserver '119.29.29.29'

config nameserver
	option enabled '0'
	option type 'fallback'

config nameserver_policy
	option enabled '0'
	option matcher 'geosite:cn'
	list nameserver '223.5.5.5'
	list nameserver '119.29.29.29'

config sniff
	option enabled '1'
	option protocol 'HTTP'
	list port '80'
	list port '443'
	list port '8080-8880'
	option overwrite_destination '1'

config sniff
	option enabled '1'
	option protocol 'TLS'
	list port '443'
	list port '8443'
	option overwrite_destination '1'

config sniff
	option enabled '1'
	option protocol 'QUIC'
	list port '443'
	list port '8443'
	option overwrite_destination '1'

config hosts
	option enabled '1'
	option domain_name 'mywifi.com'
	list ip '127.0.0.1'

config hosts
	option enabled '1'
	option domain_name 'dns.alidns.com'
	list ip '223.5.5.5'
	list ip '223.6.6.6'
	list ip '2400:3200:baba::1'
	list ip '2400:3200::1'

config hosts
	option enabled '1'
	option domain_name 'doh.pub'
	list ip '120.53.53.53'
	list ip '2402:4e00::'

config hosts
	option enabled '1'
	option domain_name 'dns.google'
	list ip '8.8.8.8'
	list ip '8.8.4.4'
	list ip '2001:4860:4860::8888'
	list ip '2001:4860:4860::8844'

config hosts
	option enabled '0'
	option domain_name 'cloudflare-dns.com'
	list ip '1.1.1.1'
	list ip '1.0.0.1'
	list ip '2606:4700:4700::1111'
	list ip '2606:4700:4700::1001'

config hosts
	option enabled '0'
	option domain_name 'cdn.jsdelivr.net'
	list ip 'cdn.jsdelivr.net.cdn.cloudflare.net'

config hosts
	option enabled '1'
	option domain_name 'nikkinikki.pages.dev'
	list ip '172.66.44.100'
	list ip '172.66.47.156'
	list ip '2606:4700:310c:0:0:0:ac42:2f9c'
	list ip '2606:4700:310c:0:0:0:ac42:2c64'

config lan_access_control
	option enabled '1'
	list ip '192.168.6.1/24'
	option proxy '1'

config lan_access_control
	option enabled '1'
	list ip '192.168.5.1/24'
	option proxy '1'

config lan_access_control
	option enabled '1'
	list ip '192.168.4.1/24'
	option proxy '1'

config lan_access_control
	option enabled '1'
	list ip '192.168.3.1/24'
	option proxy '1'

config router_access_control
	option enabled '1'
	list user 'dnsmasq'
	list user 'ftp'
	list user 'logd'
	list user 'network'
	list user 'nobody'
	list user 'ntp'
	list user 'ubus'
	list group 'dnsmasq'
	list group 'ftp'
	list group 'logd'
	list group 'network'
	list group 'nogroup'
	list group 'ntp'
	list group 'ubus'
	list cgroup 'adguardhome'
	list cgroup 'aria2'
	list cgroup 'dnsmasq'
	list cgroup 'netbird'
	list cgroup 'network'
	list cgroup 'qbittorrent'
	list cgroup 'sysntpd'
	list cgroup 'tailscale'
	list cgroup 'zerotier'
	option proxy '1'

config editor 'editor'

config log 'log'
